bind: ":3000"

mqtt:
  brokers:
    - "mqtt://127.0.0.1:1883"
  client_id: "atm-backend"

  topics: # ATM devices' topics
    - "moneyacceptord"
    - "codescannerd"

log_format: "pretty"
log_file: "log.txt"

# Mainnet or stagenet.
mode: "mainnet"

# This is the ATM fee percentage. For example 0.1 is 10% fee.
fee: 0.1

# Address of remote MoneroPay instance.
moneropay: "http://localhost:5000"

# Timeout for requests to MoneroPay. This option is important especially if the
# ATM is located somewhere with poor network speeds.
moneropay_timeout: "3m"

# Check MoneroPay's /health this often.
moneropay_health_poll_frequency: "10s"

# Fetch the price value from Kraken this often.
price_poll_frequency: "10s"

# Send price data to frontend this often.
price_notification_frequency: "2s"

# Supported currency or currencies
currencies:
  - "EUR"
  - "CZK"

# Rate to use if fetching it online wasn't possible.
fallback_rate: 123.45
